Try to fix specs
This is failing on Travis:

    TypeError: undefined is not a function
      at HTMLDivElement.<anonymous> (/Users/travis/build/AtomLinter/Linter/lib/linter-view.coffee:35:22)

It looks like `.hide()` is being called on Travis. This doesn't happen for me
locally, which is a bit weird, but it's easy enough to mock out `hide`.

Test Plan:

Crossed fingers. Hopefully the build works on Travis.